
service: file-sender

frameworkVersion: '3'

package:
  individually: true

plugins:
  - serverless-webpack
provider:
  stage: ${opt:stage, 'file-sender'}
  environment:
    region: 'eu-north-1'
  name: aws
  runtime: nodejs14.x
  region: ${env:AWS_DEFAULT_REGION, 'eu-north-1'}
  tracing:
    apiGateway: true
    lambda: true
  tags:
      STAGE: ${self:provider.stage}

  iam:
      role:
        statements:
          - Effect: "Allow"
            Action:
            - ses:*
            Resource: '*'

custom:
    webpack:
      includeModules:
        forceExclude:
          - aws-sdk

functions:

  sendFile:
    memorySize: 512
    timeout: 5
    handler: src/v1/lambdas/sendFile.handler
    events:
      - http:
          path: send-email
          method: post
          integration: lambda
          cors: true
          response:
            headers:
              Access-Control-Allow-Headers: "'*'"
              Access-Control-Allow-Methods: "'*'"
              Access-Control-Allow-Orogin: "'*'"